--- #YAML:1.0
name:               Win32-SysPrivilege
version:            1.46
abstract:           Perl extension for Running external programs with SYSTEM Privilege
author:
    - Baggio, Kwok Lok Chung <lokchungk@hotmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
